import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Button from "./components/Button";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <main className="bg-emerald-100 min-h-screen">
          <nav className="flex w-full p-5 text-white items-center justify-center sticky left-0 top-0 bg-linear-to-b bg-emerald-500">
            <Button path="/" label="Home" />
            <Button path="/articles" label="Articles" />
            <Button path="/posts" label="Posts" />
          </nav>
          <div className="p-5">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
